springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html

notification:
  email:
    provider: ${NOTIFICATION_EMAIL_PROVIDER:sendgrid}
  sms:
    provider: ${NOTIFICATION_SMS_PROVIDER:twilio}

jwt:
  secret: ${JWT_SECRET}
  expiration: ${JWT_EXPIRATION:86400000}

twilio:
  account-sid: ${TWILIO_ACCOUNT_SID}
  auth-token: ${TWILIO_AUTH_TOKEN}
  from-number: ${TWILIO_FROM_NUMBER}

spring:
  application:
    name: btg-funds

  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        default_schema: btg

  sendgrid:
    api-key: ${SENDGRID_API_KEY}
    from-email: ${SENDGRID_FROM_EMAIL}

  
  mongodb:
    uri: ${MONGODB_URI}

server:
  port: ${SERVER_PORT:8080}

logging:
  level:
    org.hibernate.SQL: info
    org.hibernate.orm.jdbc.bind: trace
    org.mongodb.driver: info