name: BTG Funds CI

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:

  build:
    runs-on: ubuntu-latest

    steps:

      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'  
          cache: maven

      - name: Give permission to mvnw
        run: chmod +x mvnw

      - name: Run tests
        run: ./mvnw clean test

      - name: Build project
        run: ./mvnw clean package -DskipTests

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: btg-funds-jar
          path: target/*.jar